name: Tests

on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Ruff lint check
        run: ruff check .

      - name: Run tests
        run: python -m pytest

      - name: build docker image
        run: docker build -t ghcr.io/aurelius-nox/pytest:latest .

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ghcr.io/aurelius-nox/pytest:latest
